//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ERPService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ERPService.IERPService")]
    public interface IERPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IERPService/OpenConnection", ReplyAction="http://tempuri.org/IERPService/OpenConnectionResponse")]
        bool OpenConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IERPService/ExecuteScalar", ReplyAction="http://tempuri.org/IERPService/ExecuteScalarResponse")]
        object ExecuteScalar(string sql);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IERPServiceChannel : WindowsFormsApplication1.ERPService.IERPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ERPServiceClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ERPService.IERPService>, WindowsFormsApplication1.ERPService.IERPService {
        
        public ERPServiceClient() {
        }
        
        public ERPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ERPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool OpenConnection() {
            return base.Channel.OpenConnection();
        }
        
        public object ExecuteScalar(string sql) {
            return base.Channel.ExecuteScalar(sql);
        }
    }
}
